// <auto-generated />
namespace VinylShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DelAdmin_Requaried : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DelAdmin_Requaried));
        
        string IMigrationMetadata.Id
        {
            get { return "202308111237192_DelAdmin_Requaried"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
